services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - postgres

  php:
    build: ./php
    volumes:
      - ./app:/var/www/html
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: xbuy
    volumes:
        - ./docker/postgres/:/docker-entrypoint-initdb.d/

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "support@xbuy.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
    depends_on:
      - postgres


volumes:
  pg_data:
